name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build JAR (skip tests for speed)
        run: mvn -B -ntp -DskipTests package
        env:
          MAVEN_OPTS: -XX:+EnableDynamicAgentLoading

      - name: Create GitHub Release & Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
